title: Burnley-Moran School PTO
email: burnleymoranpto@gmail.com
description: >
  The Burnley-Moran Parent Teacher Organization is a non-profit aimed at
  fostering a vibrant school community and supporting quality education for
  all Burnley-Moran students.

github:
  organization: Burnley-Moran-PTO
  repository: Burnley-Moran-PTO.github.io
  default_branch: master

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"

collections:
  events:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/

sass:
  sass_dir: _sass

styles:
  - /assets/main.css
  
kramdown:
  hard_wrap: true

exclude:
  - assets/*.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
