title: Burnley-Moran School PTO
email: burnleymoranpto@gmail.com
description: >
  The Burnley-Moran Parent Teacher Organization is a non-profit aimed at
  fostering a vibrant school community and supporting quality education for
  all Burnley-Moran students.

plugins:
  - jekyll-remote-theme

remote_theme: 18f/uswds-jekyll@38f6d3ceac7a04fa6d53ebcbaace81b909ea5801

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

collections:
  events:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/

styles:
  - /assets/css/main.css
  
kramdown:
  hard_wrap: true

exclude:
  - assets/*.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
