title: Burnley-Moran School PTO
email: burnleymoranpto@gmail.com
description: >
  The Burnley-Moran Parent Teacher Organization is a non-profit aimed at
  fostering a vibrant school community and supporting quality education for
  all Burnley-Moran students.
baseurl: ""
url: "http://burnleymoranpto.org"

github:
  organization: Burnley-Moran-PTO
  repository: Burnley-Moran-PTO.github.io
  default_branch: master

theme: jekyll-uswds

sass:
  sass_dir: _sass

styles:
  - /assets/main.css

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
