title: Burnley-Moran School PTO
email: burnleymoranpto@gmail.com
description: >
  The Burnley-Moran Parent Teacher Organization is a non-profit aimed at
  fostering a vibrant school community and supporting quality education for
  all Burnley-Moran students.

github:
  organization: Burnley-Moran-PTO
  repository: Burnley-Moran-PTO.github.io
  default_branch: master

plugins:
  - jekyll-remote-theme

remote_theme: 18f/uswds-jekyll

styles:
  - /assets/main.css

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "assets/uswds"
    values:
      skip_index: true

collections:
  events:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:path/

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
